name: Pipeline
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  sast:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: apt update && apt install -y build-essential python3-dev python3-pip default-libmysqlclient-dev git
      - run: pip install -e ".[dev]"
      # - run: make dist
      - run: make sast

  trivy:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/aquasec/trivy:latest
    steps:
      - uses: actions/checkout@v3
      - run: apk update
      - run: apk add make
      - run: trivy --version
      - run: sh ./scripts/trivy_scan_repo.sh

  secrets_scan:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/airtai/airt-service-dev:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: make check_git_history_for_secrets

  detect_secrets:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: apt update && apt install -y build-essential python3-dev python3-pip default-libmysqlclient-dev git
      - run: pip install -e ".[dev]"
      # - run: make dist
      - run: make detect_secrets
